spring.application.name=Gestao_de_Contas
# Conexão com o Banco
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_dividas
spring.datasource.username=admin
spring.datasource.password=admin

# Conexão com RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.threads.virtual.enabled=true

security.token=token_seguranca_gestao_apenas

# Se tiver senha:
spring.data.redis.password=sua_senha_aqui
# Timeout de conexão
spring.data.redis.timeout=2000ms
